services:
    laravel.test:
        build:
            context: ./docker/8.2
            dockerfile: Dockerfile
            target: develop
            args:
                WWWGROUP: '${WWWGROUP}'
                WWWUSER: '${WWWUSER}'
        image: malusevd99/website
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            APP_ENV: '${APP_ENV}'
        volumes:
            - .:/var/www/html
        networks:
            - dusan_malusev
        depends_on:
            - pgsql
            - redis
            - minio
            - meilisearch
            - mailpit
            - selenium
            - soketi
    pgsql:
        image: 'postgres:15-alpine'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'dusan_malusev-pgsql:/var/lib/postgresql/data'
            - './docker/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
            - './docker/pgsql/create-umami-database.sql:/docker-entrypoint-initdb.d/10-create-umami-database.sql'
        networks:
            - dusan_malusev
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - '${DB_DATABASE}'
                - '-U'
                - '${DB_USERNAME}'
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        networks:
            - dusan_malusev
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    minio:
        image: 'minio/minio:latest'
        ports:
            - '${FORWARD_MINIO_PORT:-9000}:9000'
            - '${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900'
        environment:
            MINIO_ROOT_USER: dusan_malusev
            MINIO_ROOT_PASSWORD: password
        volumes:
            - 'dusan_malusev-minio:/data/minio'
        networks:
            - dusan_malusev
        command: 'minio server /data/minio --console-address ":8900"'
        healthcheck:
            test:
                - CMD
                - curl
                - '-f'
                - 'http://localhost:9000/minio/health/live'
            retries: 3
            timeout: 5s
    meilisearch:
        image: 'getmeili/meilisearch:latest'
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        volumes:
            - 'dusan_malusev-meilisearch:/meili_data'
        networks:
            - dusan_malusev
        healthcheck:
            test:
                - CMD
                - wget
                - '--no-verbose'
                - '--spider'
                - 'http://localhost:7700/health'
            retries: 3
            timeout: 5s
    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - dusan_malusev
    selenium:
        image: selenium/standalone-chrome
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - '/dev/shm:/dev/shm'
        networks:
            - dusan_malusev
    soketi:
        image: 'quay.io/soketi/soketi:latest-16-alpine'
        environment:
            SOKETI_DEBUG: '${SOKETI_DEBUG:-1}'
            SOKETI_METRICS_SERVER_PORT: '9601'
            SOKETI_APP_MANAGER_DRIVER: 'postgres'
            SOKETI_APP_MANAGER_CACHE_ENABLED: true
            SOKETI_APP_MANAGER_CACHE_TTL: 3600
            SOKETI_DB_REDIS_HOST: ${REDIS_HOST:-redis}
            SOKETI_DB_REDIS_PORT: ${REDIS_PORT:-6379}
            SOKETI_DB_REDIS_DB: ${REDIS_SOCKETI_DB:-3}
            SOKETI_DB_REDIS_PASSWORD: ${REDIS_PASSWORD:-null}
            SOKETI_DB_POSTGRES_HOST: ${DB_HOST:-pgsql}
            SOKETI_DB_POSTGRES_PORT: ${DB_PORT:-5432}
            SOKETI_DB_POSTGRES_USERNAME: ${DB_USERNAME:-dusan_malusev}
            SOKETI_DB_POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
            SOKETI_DB_POSTGRES_DATABASE: ${DB_DATABASE:-dusan_malusev}
            SOKETI_APP_MANAGER_POSTGRES_TABLE: 'socketi_apps'
            SOKETI_APP_MANAGER_POSTGRES_VERSION: '15'
            SOKETI_DB_POOLING_ENABLED: true
            SOKETI_DB_POOLING_MIN: 1
            SOKETI_DB_POOLING_MAX: 100
            SOKETI_METRICS_ENABLED: 1
            SOKETI_CACHE_DRIVER: 'memory'
            SOKETI_QUEUE_DRIVER: 'redis'
            SOKETI_QUEUE_REDIS_CONCURRENCY: 10
        ports:
            - '${PUSHER_PORT:-6001}:6001'
            - '${PUSHER_METRICS_PORT:-9601}:9601'
        networks:
            - dusan_malusev
    umami:
        image: ghcr.io/umami-software/umami:postgresql-latest
        ports:
          - "3000:3000"
        environment:
          DATABASE_URL: 'postgresql://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/umami'
          DATABASE_TYPE: postgresql
          APP_SECRET: '${UMAMI_APP_SECRET}'
        depends_on:
          - pgsql
        restart: unless-stopped
        networks:
            - dusan_malusev
networks:
    dusan_malusev:
        driver: bridge
volumes:
    dusan_malusev-pgsql:
        driver: local
    dusan_malusev-redis:
        driver: local
    dusan_malusev-minio:
        driver: local
    dusan_malusev-meilisearch:
        driver: local
