services:
  nginx:
    image: 'ghcr.io/malusevdevelopment/nginx:${VERSION:-latest}'
    build:
      context: ../
      dockerfile: deploy/nginx/Dockerfile
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - soketi
      - umami
      - website
    ports:
      - '80:80'
      - '443:443'
    networks:
      - website
    secrets:
     - dusanmalusev.dev.fullchain.pem
     - dusanmalusev.dev.privkey.pem
     - dusanmalusev.dev.chain.pem
     - statistics.dusanmalusev.dev.fullchain.pem
     - statistics.dusanmalusev.dev.privkey.pem
     - statistics.dusanmalusev.dev.chain.pem
     - live.dusanmalusev.dev.fullchain.pem
     - live.dusanmalusev.dev.privkey.pem
     - live.dusanmalusev.dev.chain.pem

    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.loadbalancer == true
  soketi:
    image: 'quay.io/soketi/soketi:latest-16'
    container_name: soketi
    stop_signal: SIGINT
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - pgsql
      - valkey
    networks:
      - website
    ports:
      - '6001:6001'
    env_file:
      - soketi.env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
  valkey:
    image: 'ghcr.io/malusevdevelopment/valkey:${VERSION:-latest}'
    build:
      context: ../
      dockerfile: deploy/valkey/Dockerfile
    restart: unless-stopped
    deploy:
      mode: global
      placement:
        constraints:
          - node.valkey == true
    volumes:
      - 'valkey:/data'
    networks:
      - website
    secrets:
      - valkey.users
  umami:
    image: ghcr.io/umami-software/umami:postgresql-v2.15
    container_name: umami
    restart: unless-stopped
    stop_signal: SIGINT
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - website
    ports:
      - '3000:3000'
    env_file:
      - umami.env
  scheduler:
    image: 'ghcr.io/malusevdevelopment/website:${VERSION:-latest}'
    container_name: scheduler
    stop_signal: SIGINT
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    working_dir: /var/www/html
    command: start-container php artisan schedule:work -n --ansi
    extra_hosts:
        - 'host.docker.internal:host-gateway'
    env_file:
      - website.env
    environment:
      LARAVEL_SAIL: 0
      XDEBUG_MODE: 'off'
      SERVER_NAME: www.dusanmalusev.dev
    networks:
      - website
    depends_on:
      - valkey
      - umami
      - soketi
  horizon:
    image: 'ghcr.io/malusevdevelopment/website:${VERSION:-latest}'
    container_name: horizon
    working_dir: /var/www/html
    command: start-container php artisan pulse:check -n --ansi
    stop_signal: SIGINT
    extra_hosts:
        - 'host.docker.internal:host-gateway'
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      mode: replicated
      replicas: 1
    env_file:
      - website.env
    environment:
      LARAVEL_SAIL: 0
      XDEBUG_MODE: 'off'
      SERVER_NAME: www.dusanmalusev.dev
    networks:
      - website
    depends_on:
      - valkey
      - umami
      - soketi
  pulse-check:
    image: 'ghcr.io/malusevdevelopment/website:${VERSION:-latest}'
    container_name: pulse-check
    working_dir: /var/www/html
    stop_signal: SIGINT
    command: start-container php artisan pulse:check -n --ansi
    extra_hosts:
        - 'host.docker.internal:host-gateway'
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    env_file:
      - website.env
    environment:
      LARAVEL_SAIL: 0
      XDEBUG_MODE: 'off'
      SERVER_NAME: www.dusanmalusev.dev
    networks:
      - website
    depends_on:
      - valkey
      - umami
      - soketi
  pulse-work:
    image: 'ghcr.io/malusevdevelopment/website:${VERSION:-latest}'
    container_name: pulse-work
    stop_signal: SIGINT
    working_dir: /var/www/html
    command: start-container php artisan pulse:work -n --ansi
    extra_hosts:
        - 'host.docker.internal:host-gateway'
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    env_file:
      - website.env
    environment:
      LARAVEL_SAIL: 0
      XDEBUG_MODE: 'off'
      SERVER_NAME: www.dusanmalusev.dev
    networks:
      - website
    depends_on:
      - valkey
      - umami
      - soketi
  sqs:
    image: 'ghcr.io/malusevdevelopment/website:${VERSION:-latest}'
    container_name: sqs
    working_dir: /var/www/html
    command: start-container php artisan queue:work sqs --max-jobs=1000 --sleep=3 --tries=3 --max-time=3600
    extra_hosts:
        - 'host.docker.internal:host-gateway'
    stop_signal: SIGINT
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    env_file:
      - website.env
    environment:
      LARAVEL_SAIL: 0
      XDEBUG_MODE: 'off'
      SERVER_NAME: www.dusanmalusev.dev
    networks:
      - website
    depends_on:
      - valkey
      - umami
      - soketi
  website:
    image: 'ghcr.io/malusevdevelopment/website:${VERSION:-latest}'
    build:
      context: ../
      dockerfile: docker/php/Dockerfile
      target: production
    container_name: website
    working_dir: /var/www/html
    command: start-container php artisan octane:frankenphp --host=0.0.0.0 --port=8080 --admin-host=0.0.0.0 --admin-port=2019 --watch --log-level=debug --max-requests=1000
    stop_signal: SIGINT
    extra_hosts:
        - 'host.docker.internal:host-gateway'
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - '8000:8080'
      - '2019:2019'
    env_file:
      - website.env
    environment:
      LARAVEL_SAIL: 0
      XDEBUG_MODE: 'off'
      SERVER_NAME: www.dusanmalusev.dev
      XDG_CONFIG_HOME: /config
      XDG_DATA_HOME: /data
    networks:
      - website
    depends_on:
      - valkey
      - umami
      - soketi
      - horizon

volumes:
  valkey:
    driver: local

networks:
  website:
    external: true

secrets:
  dusanmalusev.dev.fullchain.pem:
    external: true
  dusanmalusev.dev.privkey.pem:
    external: true
  dusanmalusev.dev.chain.pem:
    external: true

  statistics.dusanmalusev.dev.fullchain.pem:
    external: true
  statistics.dusanmalusev.dev.privkey.pem:
    external: true
  statistics.dusanmalusev.dev.chain.pem:
    external: true

  live.dusanmalusev.dev.fullchain.pem:
    external: true
  live.dusanmalusev.dev.privkey.pem:
    external: true
  live.dusanmalusev.dev.chain.pem:
    external: true

  valkey.users:
    external: true