name: "Build Base Image"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    uses: "./.github/workflows/docker.yml"
    with:
      docker_target: base
      version: base
      platforms: linux/arm64
      dev: false
      image: ${{ vars.IMAGE }}
    secrets:
      CR_PAT: ${{ secrets.CR_PAT }}
      REGISTRY: ${{ secrets.REGISTRY }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}