name: "Base And Development Docker Images"

on:
  workflow_dispatch:
  push:
    branches: master
    paths:
      - "docker/php/**"
      - "docker/supervisord/**"
jobs:
  base:
    uses: "./.github/workflows/docker.yml"
    with:
      docker_target: base
      version: base
      platforms: linux/amd64,linux/arm64
    secrets:
      CR_PAT: ${{ secrets.CR_PAT }}
  develop:
    uses: "./.github/workflows/docker.yml"
    needs: ["base"]
    with:
      docker_target: develop
      version: dev
      platforms: linux/amd64
    secrets:
      CR_PAT: ${{ secrets.CR_PAT }}
