name: "Production/Development Images"

on:
  push:
    tags:
      - "v*"
  schedule:
    # Build base and development images on 1 and 15 day every month
    - cron: '0 0 1,15 * *'
  workflow_dispatch:

jobs:
  base:
    uses: "./.github/workflows/docker.yml"
    with:
      base: true
      platforms: linux/amd64,linux/arm64/v8
    secrets:
      CR_PAT: ${{ secrets.CR_PAT }}
      REGISTRY: ${{ secrets.REGISTRY }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
  dev:
    needs: ["base"]
    uses: "./.github/workflows/docker.yml"
    with:
      platforms: linux/amd64
      dev: true
    secrets:
      CR_PAT: ${{ secrets.CR_PAT }}
      REGISTRY: ${{ secrets.REGISTRY }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
