name: "Production Image"

on:
  workflow_call:
    inputs:
      version:
        default: ""
        required: true
        type: string
    secrets:
      CR_PAT:
        required: true
      REGISTRY:
        required: true
      REGISTRY_USERNAME:
        required: true

  workflow_dispatch:
    inputs:
      version:
        default: ""
        required: true
        type: string
jobs:
  production:
    uses: "./.github/workflows/docker.yml"
    with:
      docker_target: production
      platforms: linux/arm64
      version: ${{ inputs.version }}
      image: ${{ vars.IMAGE }}
    secrets:
      CR_PAT: ${{ secrets.CR_PAT }}
      REGISTRY: ${{ secrets.REGISTRY }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
