name: "Release"

on:
  push:
    tags:
      - "v*"

jobs:
  tag:
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.version_tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get Tag
        if: startsWith(github.ref, 'refs/tags/v')
        uses: olegtarasov/get-tag@v2.1.3
        id: version_tag
        with:
          tagRegex: "v(.*)"
  image:
    needs: ["tag"]
    uses: "./.github/workflows/production-image.yml"
    with:
      version: ${{ needs.tag.outputs.version }}
    secrets:
      CR_PAT: ${{ secrets.CR_PAT }}
      REGISTRY: ${{ secrets.REGISTRY }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
  release:
    runs-on: ubuntu-24.04
    needs: ["tag", "image"]
    steps:
      - name: Run Nginx container
        run: docker run --name server --rm -d ghcr.io/malusevdevelopment/nginx:${{ needs.tag.outputs.version }} tail -f /dev/null
      - name: Run Website container
        run: docker run --name website --rm -d ghcr.io/malusevdevelopment/website:${{ needs.tag.outputs.version }} tail -f /dev/null
      - name: Extract the files from the containers
        run: |
          mkdir -p website
          docker cp website:/var/www/html/ website/
          docker cp server:/var/www/html/public/build website/public/build

          rm -rf website/public/build/*.map \
            website/stubs \
            website/.github \
            website/.devcontainer \
            website/.vscode \
            website/scripts \
            website/deploy \
            website/data \
            website/tests \
            website/.dockerignore \
            website/.editorconfig \
            website/.gitattributes \
            Website/.gitignore \
            website/.phpstorm.meta.php \
            website/postcss.config.js \
            website/tailwind.config.js \
            website/tailwind.website.config.js \
            website/package.json \
            website/package-lock.json \
            website/pint.json \
            website/_ide_helper_models.php \
            website/_ide_helper.php \
            website/ray.php \
            website/phpunit.xml \
            website/compose.yml

            tar -czf website.tar.gz website
      - name: Release
        uses: softprops/action-gh-release@v2
        id: release
        with:
          make_latest: true
          name: "v${{ needs.tag.outputs.version }}"
          tag_name: "v${{ needs.tag.outputs.version }}"
          generate_release_notes: true
          append_body: true
          prerelease: false
          fail_on_unmatched_files: true
          files: |
            website.tar.gz
